### ISSUE TITLE
adding "dynamic-body" to custom component doesn't create a proper collider

### ISSUE THREAD

**Issue by ELI7VH** [n5ro/aframe-physics-system#154]
when my sphere hits the 'ground' it does the expected and bounces in place.

When my custom THREE.BoxGeometry hits the ground ,it's a far different story. It bounces off at some crazy angle. 

code: https://glitch.com/~eli7vh-aframe-hello-world

**Comment by Galadirith** [comment]
@ELI7VH thanks for opening your issue, I'm sorry it's taken so long to reply.

The link you provided to an example of your issue doesn't work anymore. Could I please ask you to recreate the example and send a new link. Or if you prefer you could provide a more detailed description of your issue, with enough information so that I can reproduce your issue.

Based on what you've said it sounds like there is a very small asymmetry in your custom geometry, and due to the _random_ discrete time steps (because of small variations in frame times) that are used for the physics simulation, it appears like the custom geometry bounces at different angles when you re-evaluate your example.

I would be very happy to take a proper look at you example when you are able to provide it 😊

**Comment by ELI7VH** [comment]
thanks @Galadirith that is actually helpful. I will keep that in mind for future stuff. 

Let's close this for now, and I will re-open if i see the issue again! :)
