### ISSUE TITLE
Cones have Inverted physics

### ISSUE THREAD

**Issue by VGBoy** [n5ro/aframe-physics-system#160]
While testing something with dynamic bodies and static bodies. I have found that dynamic body physics are inverted for cone primitives. This seems to only apply to those shapes, as others have proper hitboxes.
[Cone Physics Reversed.zip](https://github.com/donmccurdy-up-for-adoption/aframe-physics-system/files/5204984/Cone.Physics.Reversed.zip)

**Comment by MignonBelongie** [comment]
See https://github.com/donmccurdy/three-to-cannon/pull/27
Unfortunately, even if it gets fixed right away, it won't immediately fix the problem here, since we're not (yet) using the latest version of three-to-cannon.
If you need a temporary workaround, you can edit your local copy of aframe-physics-system/node_modules/three-to-cannon/dist/three-pathfinding.js, replacing 90 with -90.
